"""Project the public-domain Natural Earth land outlines for the story map."""
import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent


def clip(ring, axis, edge, keep_greater):
    result = []
    previous = ring[-1]
    previous_inside = (previous[axis] >= edge) if keep_greater else (previous[axis] <= edge)
    for point in ring:
        inside = (point[axis] >= edge) if keep_greater else (point[axis] <= edge)
        if inside != previous_inside:
            ratio = (edge - previous[axis]) / (point[axis] - previous[axis])
            result.append([previous[i] + ratio * (point[i] - previous[i]) for i in range(2)])
        if inside:
            result.append(point)
        previous, previous_inside = point, inside
    return result


def mercator(latitude):
    return math.log(math.tan(math.pi / 4 + math.radians(latitude) / 2))


def project(point):
    longitude, latitude = point
    return ((longitude - 100) / 39 * 400 + 16,
            (mercator(51) - mercator(latitude)) / (mercator(51) - mercator(24)) * 312 + 20)


source = json.loads((HERE / 'ne_110m_land.geojson').read_text())
paths = []
for feature in source['features']:
    geometry = feature['geometry']
    polygons = [geometry['coordinates']] if geometry['type'] == 'Polygon' else geometry['coordinates']
    for polygon in polygons:
        for ring in polygon:
            for axis, edge, greater in [(0, 98, True), (0, 141, False), (1, 22, True), (1, 53, False)]:
                if ring:
                    ring = clip(ring, axis, edge, greater)
            if len(ring) >= 3:
                points = [project(point) for point in ring]
                paths.append('M' + 'L'.join(f'{x:.1f},{y:.1f}' for x, y in points) + 'Z')

target = HERE.parents[2] / 'client/src/assets/story-04-map-land.ts'
target.write_text('// Natural Earth 1:110m land, public domain. See design/story-04/map/.\n'
                  '// Generated by design/story-04/map/prepare.py; no country borders.\n'
                  f'export const storyMapLand = {json.dumps("".join(paths))};\n')
print(f'{target}: {len(paths)} polygons')
for point in [(110, 38), (125.5, 45), (127, 37.5), (118.5, 32), (128.7, 35.7)]:
    print(point, tuple(round(value, 1) for value in project(point)))
